# Generated by Django 4.2.10 on 2024-02-21 14:48

from django.db import migrations
from django.core.management import call_command

def load_initial_data(apps, schema_editor):
    call_command(
        "loaddata",
        "experience.json",
        app_label="users",
    )

def unload_initial_data(apps, schema_editor):
    CountryModel = apps.get_model("users","Experience")
    CountryModel.objects.all().delete()
    

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_Load_Country'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, unload_initial_data),
    ]