# Generated by Django 4.2.10 on 2024-02-21 14:48

from django.db import migrations
from django.core.management import call_command


def load_initial_data(apps, schema_editor):
    call_command(
        "loaddata",
        "article_status.json",
        app_label="articles",
    )

def unload_initial_data(apps, schema_editor):
    ArticleStatusModel = apps.get_model("articles","ArticleStatus")
    ArticleStatusModel.objects.all().delete()
    


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, unload_initial_data),
    ]
