# Generated by Django 4.2.10 on 2024-02-21 14:48

from django.db import migrations
from django.core.management import call_command


def load_initial_data(apps, schema_editor):
    call_command(
        "loaddata",
        "request_status.json",
        app_label="articles",
    )

def unload_initial_data(apps, schema_editor):
    RequestStatusModel = apps.get_model("articles","ReviewRequestStatus")
    RequestStatusModel.objects.all().delete()
    

class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_Load_Article_Status'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, unload_initial_data),
    ]
