# Generated by Django 4.2.10 on 2024-02-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0004_Load_Interests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="website",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
